# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20160801_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='collection',
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
