# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20160802_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_name',
            field=models.CharField(max_length=200),
        ),
    ]
