# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20160803_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img_name',
            new_name='title',
        ),
    ]
